### ISSUE TITLE
format astuces

### ISSUE THREAD

**Issue by abithekid** [Mrwebfr/SosPromo#23]
Les astuces fonctionnent comme des articles a ceci près que la liste des astuces devraient mettre clairement en évidence le système de vote comme ici :+1: 
![astuces](https://cloud.githubusercontent.com/assets/12170616/7409792/a845063a-ef29-11e4-8bdf-ec1a73b7d938.JPG)

Sinon j'aurais aimé savoir si il était compliqué de présenter les infos (genre : 10 astuces pour faire donner la pate à son toutou) comme ça : (ya de plus en plus de sites qui présentent en multi pages/carousel j'ai l'impression ce genre de contenu)

http://www.msn.com/fr-fr/lifestyle/style/10-outils-ludiques-pour-d%C3%A9truire-la-cellulite/ss-BBiRgBY#image=2

**Comment by Mrwebfr** [comment]
Ok pour le vote sur les pages archives.

C'est possible avec un module de carrousel, sauf que c'est difficile à gérer coté Admin qd tu as 10000 astuces ...
De plus les sites d'infos qui présentent leurs contenus textes dans des carrousel je ne prends pas le temps de lire et vais sur un autre site, et toi ? Obligé de faire 10clics pour lire 20 phrases c'est anti-accessibilité.
C'est juste joli ou tu trouves ça pratique ?
