### ISSUE TITLE
Bon plan - fonctionnement et look

### ISSUE THREAD

**Issue by abithekid** [Mrwebfr/SosPromo#25]
Le bon plan sera tjs accompagné d'une image, dans les widgets on peut conserver le format d'image miniature mais en coeur de page il faut que l'image aie plus de place...

Un bon plan peut présenter soit un code, soit renvoyer vers le site directement
Un bon plan peut être : une offre exceptionnelle, un cadeau offert, offre parannaige, un cashbak etc.

![bon plan](https://cloud.githubusercontent.com/assets/12170616/7410336/210d44c0-ef2e-11e4-877e-1f8df76319c5.JPG)

**Comment by Mrwebfr** [comment]
Vu
Attention ton image est au format panoramique, pas du tout pratique pour trouver des photos adaptées aux dimensions ...
