### ISSUE TITLE
Header blog et pages internes

### ISSUE THREAD

**Issue by abithekid** [Mrwebfr/SosPromo#32]
En fait on va mettre le menu scroll partout, ca permet de gagner de la place pour les contenus les plus importants, pubs...contenu de la page...
![page interne blog](https://cloud.githubusercontent.com/assets/12170616/7493035/ba99f240-f3fd-11e4-9f1f-6d9292847988.JPG)

**Comment by Mrwebfr** [comment]
La bannière sera administrable par post-type ;) Pas de soucis ...

**Comment by abithekid** [comment]
euh mais tu parles de quelle bannière ?

**Comment by Mrwebfr** [comment]
Menu scroll = Menu simple sans bannière
Menu avec bannière = Menu avec bannière

Les 2 sont liés vu que la présentation du menu dépend de l'affichage de la bannière
