### ISSUE TITLE
Page articles du blog - Erratum 

### ISSUE THREAD

**Issue by abithekid** [Mrwebfr/SosPromo#38]
il faut toujours tester avec les pubs, ya que comme ça qu'on se rend vraiment compte ! Voilà comme ça j'ai bossé la présentation pour les articles, tu vas pas etre tres content mais après nos conversations j'ai encore bossé le header et j'en arrive a cette conclusion !

Barre rouge en haut
Menu scroll en 2
pub en 3
fil ariane 4
entourage de l'article en gris avec titre banda gris très foncé et infos grises plus claires juste en dessous et les outils de partage entre le titre et le texte.
![articles blog css](https://cloud.githubusercontent.com/assets/12170616/7503684/e2603f7c-f444-11e4-9cf9-1c19930f0b6a.JPG)

**Comment by Mrwebfr** [comment]
> ok pour les modifs ce jeudi 
> sauf pour les réseaux sociaux au dessus du menu que je ferais la semaine prochaine, obligé de refaire tout le fonctionnement du scroll / menu ...

**Comment by abithekid** [comment]
Ok pas de soucis, tu pourras rajouter la top barre à la fin, pas urgent, 
je t'envoie les autres modeles de pages sur ce principe dans la soirée
*Abigaïl Cherrier*
Chef de projets communication
www.terreweb.net <http://www.terreweb.net> - ac@terreweb.net 
<mailto:ac@terreweb.net> - Tel : 09 52 40 31 13 / Mob 06 73 55 93 44

logo Agence Terreweb <http://www.terreweb.net>

______
Tout usage de ce message par une personne autre que son destinataire est 
strictement interdit. L'intégrité de ce message n'étant pas assurée sur 
Internet, la société GreenFizz Communication ne peut être tenue pour 
responsable de son contenu.Toute modification ou diffusion non autorisée 
est interdite. Si vous n'êtes pas destinataire de ce message, veuillez 
le détruire et avertir l'expéditeur. The information above is for the 
sole use of the individual or entity to which it is intended. If you are 
not the intended recipient of this message, you are here by notified 
that any dissemination, any alteration, distribution or copying of this 
document is strictly prohibited. The integrity of this message cannot be 
guaranteed on the Internet, GreenFizz Communication, shall in no way be 
liable for its content. If this message was not meant to you please 
destroy it and notify the sender.

**Comment by Mrwebfr** [comment]
> J'ai mis la bordure juste à gauche, c'est plus joli mais on peut encadrer si tu n'aimes pas
> Le fil d'arianne et la pub sont une autre mission pour la semaine pro.
