### ISSUE TITLE
bug image bon plan widget + option affichage logo/image au lieu des infos de réduction

### ISSUE THREAD

**Issue by abithekid** [Mrwebfr/SosPromo#42]
L'animation avec l'image du bon plan est pas OK

Sinon as tu pensé à rajouté l'option d'affichage soit images/logo en premier soit l'info texte , qu'on puisse varier selon là où on place le widget codes live ?

![bon plan bug image](https://cloud.githubusercontent.com/assets/12170616/7503986/ef8e3b2a-f446-11e4-8dbb-e9174ed0e433.JPG)

=====================
 bug CSS padding quand texte de 3 lignes widget codes promo #41 

![code promo widgt](https://cloud.githubusercontent.com/assets/12170616/7503945/87757f9e-f446-11e4-88d2-6e4ff13b3c46.JPG)

**Comment by Mrwebfr** [comment]
> Bonne idée, je vais ajouter l'option puis revoir le délai de l'animation afin d'éviter la superposition.
