### ISSUE TITLE
bug affichage vignettes logo marques sur page résultats de recherche

### ISSUE THREAD

**Issue by abithekid** [Mrwebfr/SosPromo#7]
Quans on ouvre le menu scroll en milieu de page, les vignettes passent devant le menu

![bug images sos](https://cloud.githubusercontent.com/assets/12170616/7391836/1c3488b4-ee84-11e4-9315-3a462351b8c6.png)

**Comment by Mrwebfr** [comment]
Problème de Z-index.
- à suivre avec : https://github.com/Mrwebfr/SosPromo/issues/4

**Comment by Mrwebfr** [comment]
Corrigé via z-index
